[package]
name = "lib"
version = "0.1.0"
authors = ["shino16 <ms_020916@yahoo.co.jp>"]
edition = "2018"

[dependencies]

[lib]
name = "lib"
path = "src/lib.rs"

[[bin]]
name = "cprbin"
path = "src/main.rs"
doc = false
