# rustfmt 2.0.0-rc.2-nightly
unstable_features = true
condense_wildcard_suffixes = true
format_macro_matchers = true
format_strings = true
match_arm_blocks = false
match_block_trailing_comma = true
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true

# hard_tabs = true
hard_tabs = false

# max_width = 99
# chain_width = 89
# single_line_if_else_max_width = 80
# struct_lit_width = 60
# fn_single_line = true
# width_heuristics = "Max"

max_width = 80
chain_width = 60
single_line_if_else_max_width = 50
struct_lit_width = 18
fn_single_line = false
width_heuristics = "Scaled"
