# rustfmt 2.0.0-rc.2-nightly
unstable_features = true
chain_width = 89
condense_wildcard_suffixes = true
# fn_single_line = true
format_macro_matchers = true
format_strings = true
# imports_indent = "Visual"
match_arm_blocks = false
match_block_trailing_comma = true
max_width = 97
overflow_delimited_expr = true
single_line_if_else_max_width = 50
struct_lit_width = 40
use_field_init_shorthand = true
wrap_comments = true
# width_heuristics = "Max"