[languages.rs]
verification_file_suffix = '_test.rs'
compile = 'cargo build --release --workspace'
execute = 'bash ".verify-helper/execute.sh" {path}'
list_dependencies = 'bash ".verify-helper/list_dependencies.sh" {path}'