name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Rust (1.42.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0
          profile: minimal

      - name: Build
        run: cargo build --verbose

      - name: Run tests
        run: cargo test --verbose -- --test-threads=1

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install oj-verify
        run: pip3 install -U online-judge-verify-helper

      - name: Setup Rust (1.42.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0
          profile: minimal

      - name: Setup Rust (nightly)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal

      - name: Setup cargo-mod-deps
        run: cargo install --git https://github.com/shino16/cargo-mod-deps.git --branch main


      - name: oj-verify
        run: oj-verify all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
