name: test

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Python
        uses: actions/setup-python@v1

      - name: Install oj-verify
        run: pip3 install git+https://github.com/shino16/verification-helper

      - name: Setup Rust (1.42.0)
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.42.0
          profile: minimal

      - name: Build tests
        run: cargo build --release --tests

      - name: Setup cargo-auto-bundle
        run: cargo install --git https://github.com/shino16/cargo-auto-bundle.git

      - name: oj-verify
        run: oj-verify --config-file .verification-helper/config.toml all
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          YUKICODER_TOKEN: ${{ secrets.YUKICODER_TOKEN }}
          GH_PAT: ${{ secrets.GH_PAT }}
